# funding_data.py

FUNDING_DATA = [
    {"funding_option": "BMWi-Innovationsgutscheine (go-inno)", "state": ["bundesweit"], "grant_volume": 13750, "funding_quota": 50, "approval_rate": 30, "company_size": "Mittleres Unternehmen", "areas": ["Beratung", "Forschung & Innovation"], "revenue_max": 20000000, "time_required": 10, "benefit_cost_score": -9},
    {"funding_option": "Start-up BW International", "state": ["Baden-Württemberg"], "grant_volume": 20000, "funding_quota": 50, "approval_rate": 30, "company_size": "Großes Unternehmen", "areas": ["Außenwirtschaft", "Existenzgründung & -festigung"], "revenue_max": 20000000, "time_required": 10, "benefit_cost_score": -8},
    {"funding_option": "Brandenburger Innovationsfachkräfte", "state": ["Brandenburg"], "grant_volume": 29700, "funding_quota": 60, "approval_rate": 30, "company_size": "Kleinstunternehmen", "areas": ["Arbeit", "Aus- & Weiterbildung", "Forschung & Innovation", "Frauenförderung"], "revenue_max": 50000000, "time_required": 13, "benefit_cost_score": -4},
    {"funding_option": "Coaching BONUS", "state": ["Berlin"], "grant_volume": 16400, "funding_quota": 80, "approval_rate": 30, "company_size": "Mittleres Unternehmen", "areas": ["Außenwirtschaft", "Beratung", "Existenzgründung & -festigung", "Unternehmensfinanzierung"], "revenue_max": 50000000, "time_required": 13, "benefit_cost_score": -5},
    {"funding_option": "Berliner Innovationsfachkräfte", "state": ["Berlin"], "grant_volume": 20000, "funding_quota": 50, "approval_rate": 30, "company_size": "Kleinstunternehmen", "areas": ["Arbeit", "Forschung & Innovation"], "revenue_max": 50000000, "time_required": 6, "benefit_cost_score": -8},
    {"funding_option": "Digitalisierung und Arbeit 4.0", "state": ["Bremen"], "grant_volume": 5000, "funding_quota": 50, "approval_rate": 30, "company_size": "Mittleres Unternehmen", "areas": ["Beratung", "Unternehmensfinanzierung", "Digitalisierung"], "revenue_max": 50000000, "time_required": 6, "benefit_cost_score": -10},
    {"funding_option": "Digitalisierungsprämie Plus – Zuschussvariante", "state": ["Baden-Württemberg"], "grant_volume": 10000, "funding_quota": 50, "approval_rate": 30, "company_size": "Kleinstunternehmen", "areas": ["Unternehmensfinanzierung", "Digitalisierung"], "revenue_max": 50000000, "time_required": 6, "benefit_cost_score": -9},
    {"funding_option": "Entwicklungspartnerschaften mit der Wirtschaft – develoPPP Ventures", "state": ["bundesweit"], "grant_volume": 100000, "funding_quota": 50, "approval_rate": 30, "company_size": "Großes Unternehmen", "areas": ["Außenwirtschaft", "Existenzgründung & -festigung", "Frauenförderung"], "revenue_max": 50000000, "time_required": 13, "benefit_cost_score": -3},
    {"funding_option": "Förderung digitaler Spiele", "state": ["Bayern"], "grant_volume": 200000, "funding_quota": 80, "approval_rate": 30, "company_size": "Kleinstunternehmen", "areas": ["Kultur", "Medien & Sport", "Digitalisierung"], "revenue_max": 50000000, "time_required": 13, "benefit_cost_score": -1},
    {"funding_option": "GründungsBONUS – Unterstützung der Aufbauphase von Existenzgründungen und Startups", "state": ["Berlin"], "grant_volume": 50000, "funding_quota": 50, "approval_rate": 30, "company_size": "Kleines Unternehmen", "areas": ["Existenzgründung & -festigung"], "revenue_max": 10000000, "time_required": 13, "benefit_cost_score": -4},
    {"funding_option": "KMU-innovativ: Materialforschung (ProMat_KMU)", "state": ["bundesweit"], "grant_volume": 20000000, "funding_quota": 80, "approval_rate": 30, "company_size": "Großes Unternehmen", "areas": ["Forschung & Innovation", "Mobilität"], "revenue_max": 100000000, "time_required": 50, "benefit_cost_score": 7},
    {"funding_option": "Hamburg Digital", "state": ["Hamburg"], "grant_volume": 17000, "funding_quota": 30, "approval_rate": 30, "company_size": "Mittleres Unternehmen", "areas": ["Beratung", "Digitalisierung", "Unternehmensfinanzierung"], "revenue_max": 50000000, "time_required": 6, "benefit_cost_score": -9}
]